image: node

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm config set registry https://registry.npm.taobao.org
  - npm install
  - npm docs:build
  - mv docs/dist public
  artifacts:
    paths:
    - public

  only:
  - master
