language: node_js
node_js:
  - lts/*
before_script:
  - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  - git submodule init
  - git submodule update
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: github